version: '3.8'

services:
  proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
     - '80:80'
     - '443:443'
    networks:
      - nginx_ingress
      - dmz
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_moodle_conf
        target: /etc/nginx/conf.d/moodle.conf
      - source: nginx_portainer_conf
        target: /etc/nginx/conf.d/portaniner.conf
    depends_on:
        - portainer
        - moodle

  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify && --admin-password $$2y$$05$$54i9VofWuntmpdSdi9sB9O72IhpCcerLSe4VTC9vKCm3hNqOIfAh6
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]
    #command: --admin-password $2y$05$54i9VofWuntmpdSdi9sB9O72IhpCcerLSe4VTC9vKCm3hNqOIfAh6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - dmz

  portainer_agent:
    image: portainer/agent:latest
    deploy:
      mode: global   # roda em todos os nós do Swarm
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - dmz


  proxysql:
   image: proxysql/proxysql:latest
   ports:
     - "3306:6033"
   configs:
      - source: proxysql_cnf
        target: /etc/proxysql.cnf
   networks:
        dmz:
   deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure

  moodle:
    image: docker.io/manoelra66/nginx-moodle
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3
      placement:
        constraints: [node.role == worker]
    volumes:
      - moodle_data:/var/www/
    configs:
      - source: config_moodle
        target: /var/www/html/config.php
    ports:
      - "8080:8080"
    networks:
      - dmz
    depends_on:
        - proxysql

  db01:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db01
    networks:
        dmz:
    volumes:
      - docker_db01:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 10s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db01
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == worker]

  db02:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db02
    depends_on:
        - db01
    networks:
        dmz:
    volumes:
      - docker_db02:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 10s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db02
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == worker]

  db03:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db03
    depends_on:
        - db01   
        - db02
    networks:
        dmz:
    volumes:
      - docker_db03:/var/lib/mysql
    environment:
      - NODE_NAME=db03
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == worker]
configs:
  nginx_conf:
    file: ./etc/nginx/nginx.conf
  nginx_default_conf:
    file: ./etc/nginx/conf.d/default.conf
  nginx_moodle_conf:
   file: ./etc/nginx/conf.d/moodle.conf
  nginx_portainer_conf:
    file: ./etc/nginx/conf.d/portainer.conf
  proxysql_cnf:
    file: ./etc/proxysql/proxysql.cnf
  config_moodle:
    file: ./moodle/config.php

volumes:
  docker_db01:
  docker_db02:
  docker_db03:
  proxysql_data:
  portainer_data:
  moodle_data:
networks:
  nginx_ingress:
    name: nginx_ingress
    attachable: true
  dmz:
    name: dmz
    driver: overlay
    external: false
