version: '3.8'

services:
  proxy:
    image: nginx-proxy
    ports:
     - '80:80'
     - '443:443'
    networks:
      - nginx_ingress
      - backend_net
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
      - source: nginx_moodle_conf
        target: /etc/nginx/conf.d/moodle.conf
      - source: nginx_portainer_conf
        target: /etc/nginx/conf.d/portaniner.conf
  
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - admin-password-file=./etc/portainer/portainer_pass

  portainer_agent:
    image: portainer/agent:latest
    deploy:
      mode: global   # roda em todos os nós do Swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - backend_net


  proxysql:
   image: proxysql/proxysql:latest
   ports:
     - "3306:6033"
   configs:
      - source: proxysql_cnf
        target: /etc/proxysql.cnf
   networks:
        backend_net:
   deploy:
      replicas: 3
      placement:
        constraints: [node.role == node]


#  moodle:
#    image: app-moodle
#    deploy:
#      replicas: 3
#      placement:
#        constraints: [node.role == node]
#    networks:
#      - backend_net

  db01:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db01
    networks:
        backend_net:
    volumes:
      - docker_db01:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 10s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db01
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == node]

  db02:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db02
    depends_on:
        - db01
    networks:
        backend_net:
    volumes:
      - docker_db02:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin", "-uroot", "-pcloudstack", "ping"]
        interval: 10s
        timeout: 10s
        retries: 60
        start_period: 10s
    environment:
      - NODE_NAME=db02
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == node]

  db03:
    image: ustcweizhou/mariadb-cluster:latest
    hostname: db03
    depends_on:
        - db01   
        - db02

    networks:
        backend_net:
    volumes:
      - docker_db03:/var/lib/mysql
    environment:
      - NODE_NAME=db03
      - CLUSTER_ADDRESS=gcomm://db01,db02,db03
      - DB_ROOT_PASSWORD=cloudstack
      - DB_MARIABACKUP_PASSWORD=cloudstack
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == node]

volumes:
  docker_db01:
  docker_db02:
  docker_db03:
  proxysql_data:
networks:
  nginx_ingress:
    name: nginx_ingress
    attachable: true
  backend_net:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: "backend_net"
        ipam:
            driver: default

