version: '3.8'

services:
  proxy:
    image: nginxproxy/nginx-proxy:1.9
    ports:
     - '80:80'
     - '443:443'
    networks:
      - nginx_ingress
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    deploy:
      replicas: 2


networks:
  nginx_ingress:
    attachable: true

