version: '3.8'

services:
  proxy:
    image: nginxproxy/nginx-proxy:1.9
    ports:
     - '80:80'
     - '443:443'
    environment:
      - VIRTUAL_HOST=smartmeter.run.place
    networks:
      - nginx_ingress
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      replicas: 2


networks:
  nginx_ingress:
    attachable: true

