version: '3.8'

services:
  proxy:
    image: https://github.com/smartmeterdev/loadbalance/nginx-custom
    ports:
     - '80:80'
     - '443:443'
    networks:
      - nginx_ingress
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      replicas: 2


networks:
  nginx_ingress:
    attachable: true

