version: '3.8'

services:
  proxy:
    image: nginx
    ports:
     - '80:80'
     - '443:443'
   # environment:
   #   - VIRTUAL_HOST=smartmeter.run.place
    networks:
      - nginx_ingress
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == manager]

networks:
  nginx_ingress:
    attachable: true

