version: '3.8'

services: 
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      replicas: 3
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  portainer_agent:
    image: portainer/agent:latest
    deploy:
      mode: global   # roda em todos os nós do Swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent
volumes:
  portainer_data:
    driver: glusterfs
    name: "portrainer"
networks:
  portainer_agent:
    driver: overlay