version: '3.8'

services:
  master:
    image: postgres:15
    ports:
     - '5432:5432'
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: posgres
      POSTGRES_DB: mydb
      POSTGRES_MASTER_PORT: 5432
    volumes:
      - master_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"
    networks:
      - postgres_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  slave1:
    image: postgres:15
    ports:
     - '5433:5432'
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: posgres
      POSTGRES_DB: mydb
      POSTGRES_REPLICATION_MODE: slave
      POSTGRES_MASTER_HOST: master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replication_password
    volumes:
      - slave_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    deploy:
      replicas: 1


  slave2:
    image: postgres:15
    ports:
     - '5434:5432'
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: posgres
      POSTGRES_DB: mydb
      POSTGRES_REPLICATION_MODE: slave
      POSTGRES_MASTER_HOST: master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: replication_password
    volumes:
      - slave_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    deploy:
      replicas: 1


volumes:
  master_data:
  slave_data:

networks:
  postgres_network:
    external: false
